apiVersion: apps/v1
kind: Deployment
metadata:
  name: crust-deployment
  namespace: crust
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crust
  template:
    metadata:
      labels:
        app: crust
    spec:
      containers:
      - name: crust
        image: ghcr.io/m-sef/crust:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "500m"
